class structure {
    interface = {
        topMenu: {
            logo:{
                icon: 'app/img/logos/logo_192.jpg',
                text: 'jsp-malley',
            },
            links: {
                home:{activity: 'home', text: 'home',  href: ' /home/'},
                signup:{activity: 'signup', text: 'Inscription', href: '/signup/',classSuffix:'signup'},
                login:{activity: 'login', text: 'Connexion', href: '/login/',classSuffix:'login'},
                //ffcontact:{activity:'contact',text:'contact',href:'/contact/'}
            },
        },
    };
    activity = {
        home:{
            shapes:{
                slider:{
                    type:'slider',
                    options:{
                        className:'sliderFullHeight',
                        listImages:[
                            {href:'app/img/extra/slider/01.jpg'},
                            {href:'app/img/extra/slider/02.jpg'},
                            {href:'app/img/extra/slider/03.jpg'},
                            {href:'app/img/extra/slider/04.jpg'},
                        ]
                    }
                },
            }
        },
        signup:{
            shapes:{
                form:{
                    type:'form',
                },
                name:{
                    type:'input',
                    options:{
                        queryLabel:'name',
                        include:'form',
                        type:'text',
                        placeholder:'Nom',
                        notNull:true
                    }
                },
                surname:{
                    type:'input',
                    options:{
                        queryLabel:'surname',
                        include:'form',
                        type:'text',
                        placeholder:'Prénom',
                        notNull:true
                    }
                },
                email:{
                    type:'input',
                    options:{
                        queryLabel:'email',
                        include:'form',
                        type:'email',
                        placeholder:'email',
                        notNull:true
                    }
                },
                password:{
                    type:'input',
                    options:{
                        include:'form',
                        type:'password',
                        placeholder:'mot de passe',
                        queryLabel:'password',
                        notNull:true
                    }
                },
                submit:{
                    type:'submit',
                    options:{
                        queryLabel:'',
                        include:'form',
                        listInput:['name','surname','email','password'],
                        action:'put',
                        endpoint:'user',
                        error:{
                            bubble:'msg'
                        },
                    }
                }
            }
        },
        login:{
            shapes:{
                form:{
                    type:'form',
                },
                email:{
                    type:'input',
                    options:{
                        queryLabel:'email',
                        include:'form',
                        type:'email',
                        placeholder:'email',
                        notNull:true
                    }
                },
                password:{
                    type:'input',
                    options:{
                        include:'form',
                        type:'password',
                        placeholder:'mot de passe',
                        queryLabel:'password',
                        notNull:true
                    }
                },
                submit:{
                    type:'submit',
                    options:{
                        queryLabel:'',
                        content:'login',
                        include:'form',
                        listInput:['email','password'],
                        action:'auth',
                        endpoint:'user',
                        error:{
                            bubble:'msg'
                        },
                    }
                }
            }
        },
        contact:{
            shapes:{
                form:{
                    type:'form',
                },
                name:{
                    type:'input',
                    options:{
                        queryLabel:'name',
                        include:'form',
                        type:'text',
                        placeholder:'Nom',
                        notNull:true
                    }
                },
                surname:{
                    type:'input',
                    options:{
                        queryLabel:'surname',
                        include:'form',
                        type:'text',
                        placeholder:'Prénom',
                        notNull:true
                    }
                },
                email:{
                    type:'input',
                    options:{
                        queryLabel:'email',
                        include:'form',
                        type:'email',
                        placeholder:'email',
                        notNull:true
                    }
                },
                content:{
                    type:'input',
                    options:{
                        queryLabel:'content',
                        include:'form',
                        type:'textarea',
                        placeholder:'content',
                        notNull:true
                    }
                },
                /*submit:{
                    type:'submit',
                    options:{
                        queryLabel:'',
                        include:'form',
                        listInput:['name','surname','email','content'],
                        action:'put',
                        endpoint:'user',
                        error:{
                            bubble:'msg'
                        },
                    }
                }*/
            }
        }
    }
    getActivityStructure(activityId){
        console.log(this.activity[activityId]);
        return this.activity[activityId];

    }
    destroy(){
		delete(this);
	}
}